### ISSUE TITLE
Adding two or more hosts to the host parameter of the ConnectionConfig.json

### ISSUE THREAD

**Issue by lordweed92** [brendanSapience/UC4-Automic-REST-API-Delivery#5]
I'm not sure if this is close to a feature request or maybe i am just not smart enough to figure this out. I have a AWA-Env with two hosts. There are CPs running on both of those servers. I tried to alter the config-file to something like this: 
> ... 
"host":["testhost1","testhost2"], 
...

This obviously does not seem to work. Am I wrong with modelling the host parameter as an array? In addition, not every port is available on every server... Is there something I'm missing, or would this 'issue' in fact be a feature request? 

cheers,

**Comment by brendanSapience** [comment]
Hi @lordweed92,

As it stands today, you cannot have more than one host declared per "connection" in the ConnectionConfig.json file.

However, you can handle multiple hosts with it :)

here is an example: 
{"connections":
	[
	{
		"name":"AEPROD1",
		"host":"AEHostPrimary",
		"dept":"ARA",
		"lang":"E",
		"ports":["2217","2218"],
		"validity":525600,
		"RESTadmin":false
	},
	{
		"name":"AEPROD2",
		"host":"AEHostSecondary",
		"dept":"ARA",
		"lang":"E",
		"ports":["2219","2220"],
		"validity":525600,
		"RESTadmin":false
	}
	]
}
	
this way, you can attempt to connect to the first host, and if it doesnt work, connect to the second one (different connection name), etc.
