### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by hany-abdelrahman** [brendanSapience/UC4-Automic-REST-API-Delivery#6]
Are there any plans to publish the code for the Rest API. I noticed that the Java API provides much richer functionalities that are not present in the Rest API and having the source code help enriching the rest API more.

**Comment by brendanSapience** [comment]
Hi,

i realized i never replied to this.. Sure, i can add you as a contributor to the repository. are you still interested?

**Comment by brendanSapience** [comment]
this repository is now public:

**Comment by brendanSapience** [comment]
[https://github.com/brendanSapience/UC4-Automic-REST-API](url)
